### ISSUE TITLE
Allowing test mode when launching maimai

### ISSUE THREAD

**Issue by fraelyfan** [SirusDoma/MaiSense#1]
`maimai.exe` accepts an argument `gametest`, which enables the test mode hidden in the game. It would be nice if there was a way to turn it on through the launcher.
Thanks!

**Comment by SirusDoma** [comment]
The game seems didn't respond to normal input in game test, im not sure but it may related to jvs or something

but it certainly interesting to make it work, will look upon it later when im free

**Comment by SirusDoma** [comment]
Upon making touch input, i realize that i probably need to emulate hardware input in order to make the gametest sensor input working, which too much efforts for something that didn't affect the gameplay

Sorry but closing this issue
