### ISSUE TITLE
How to debug MaiSense.dll with SDEY in Visual Studio?

### ISSUE THREAD

**Issue by doublecatandpear** [SirusDoma/MaiSense#13]
Hello, I am trying to debug the MaiSense project using Visual Studio. I forked the project and made some modifications. When I try to debug it in Visual Studio, I copied the SDEY software to the debug build folder and made sure it runs properly. I set MaiSense.Launcher.exe as the target for debugging. However, the breakpoint in the dllmain() function was not hit while the breakpoint in the main() function in the MaiSense.Launcher project code was hit successfully. And the game doesn't run properly as well as I double-click to start it. I would like to know how to debug the DLL.

**Comment by SirusDoma** [comment]
The injected DLL is loaded and running within the game process, not the launcher.
You need to attach your debugger to the game instead (`maimai_dump_.exe`). Have a look at the [documentation ](https://learn.microsoft.com/en-us/visualstudio/debugger/attach-to-running-processes-with-the-visual-studio-debugger?view=vs-2022) to figure it how.  

Here's how I do it usually:
1. Put breakpoint in the launcher code, where the game process launched but in paused state ([here](https://github.com/SirusDoma/MaiSense/blob/master/src/Launcher/main.cpp#L11)).
2. Put breakpoint in `dllmain` function in dll code
3. Debug the Launcher project
4. When the 1st breakpoint hit (the one in the launcher), attach debugger to game process.
5. Resume the debug process

**Comment by doublecatandpear** [comment]
Thank you for your reply. I have debugged according to the steps, it works and fit the break point in dllMain(). But then the teaGfx window ran in full screen even though I set window mode and 1p only. I can't debug the KeyboardController 's callback function and so on. I vaguely saw several abnormal interrupts like 'Game.pdb'.

**Comment by SirusDoma** [comment]
Are you sure the game ran windowed without a debugger attached? If so, something might be wrong with your debugger. I'm uncertain, but it might affect the game working directory, which ignores the config file. I never had this issue before.

Try to [step-into and step-over](https://learn.microsoft.com/en-us/visualstudio/debugger/debugger-feature-tour?view=vs-2022) the lines after the breakpoint in `dllmain` and see where it goes.
