### ISSUE TITLE
Touch screen

### ISSUE THREAD

**Issue by HinataKato** [SirusDoma/MaiSense#2]
Hi, I want to know if this repo will support touch screen in the future?If yes, that would be too exciting

**Comment by demo0102** [comment]
I agree.

**Comment by SirusDoma** [comment]
This possible, actually i able to hook the window to became aware with touch input, however im lacking of device to test this (i don't have display with touch screen)

might do this if someone that has touch screen actually willing to assist the debugging process

**Comment by fjjking** [comment]
> 这可能，实际上我能够通过触摸输入来钩住窗口以进行感知，但是我缺乏用于测试此功能的设备（我没有触摸屏显示）
> 
> 如果有触摸屏的人实际上愿意协助调试过程，则可以这样做



> This possible, actually i able to hook the window to became aware with touch input, however im lacking of device to test this (i don't have display with touch screen)
> 
> might do this if someone that has touch screen actually willing to assist the debugging process

I'm also very interested in this, and I bought a touch screen a few days ago for exactly this kind of purpose. After the delivery arrived, I'd be happy to help.

**Comment by fraelyfan** [comment]
I'm also very interested in this, and I bought a touch screen a few days ago for exactly this kind of purpose. After the delivery arrived, I'd be happy to help.

**Comment by demo0102** [comment]
> This possible, actually i able to hook the window to became aware with touch input, however im lacking of device to test this (i don't have display with touch screen)
> 
> might do this if someone that has touch screen actually willing to assist the debugging process

I am using surface pro 4, I would like to test if I can.Another program maimai touch hack doesn't fit my device.

**Comment by SirusDoma** [comment]
Drop me message at discord if you're interested to help debugging process, I think it easier to discuss rather than here, but will push the changes to this repo regardless

I'll be sure to reply once i got free time to work on this

**Comment by honghongleong** [comment]
Hi,Just to clarify this does not support touchscreen am i right?I've recently got a HP Envy 20 TouchSmart AIO 20-d038d from a friend and would like to play maimai with touchscreen support with it.I'd love to help with the debugging process but i don't really do C++ so i'm new to it.
Discord:Asuna#8172

**Comment by SirusDoma** [comment]
Sorry it took so long, but i added touch support to the hook
This probably will be the last update, thanks
