### ISSUE TITLE
C Button?

### ISSUE THREAD

**Issue by ZhongDev** [SirusDoma/MaiSense#3]
On the cab isn't there the C button/center button?
![image](https://user-images.githubusercontent.com/47954501/75342850-554eae00-58eb-11ea-9bfd-cb87d849b651.png)
Is there a keybind for this?

**Comment by fraelyfan** [comment]
Key 0

**Comment by andylizi** [comment]
https://github.com/SirusDoma/MaiSense.API/blob/c1d60adba7b1ae4bdb931cee965513e076410b56/src/Input/dllmain.cpp#L23-L27

It's implemented but not documented for whatever reason.

**Comment by SirusDoma** [comment]
Yes, I forgot to document this, will add to readme later

**Comment by SirusDoma** [comment]
Added to README
