### ISSUE TITLE
what is  C Sensor?

### ISSUE THREAD

**Issue by HereXianggeGe** [SirusDoma/MaiSense#6]
what is  C Sensor?thanks a lot

**Comment by ZhongDev** [comment]
The C Sensor/Touch area is the center touch sensor on the Maimai Finale and lower cabinets.
(see in image)
![image](https://user-images.githubusercontent.com/47954501/75342850-554eae00-58eb-11ea-9bfd-cb87d849b651.png)

**Comment by HereXianggeGe** [comment]
thanks!in addition,Do you know what dev is?

**Comment by ZhongDev** [comment]
DEV is the mode the software is run in.
If you have the game files, there is a configuration file you can set to have Maimai run in DEV mode.

**Comment by SirusDoma** [comment]
Thanks for answering @ZhongDev, I'll closing this issue now, feel free to reopen if you had further request.  
That being said, if you have interest in non DEV mode and want to support this mod, consider to contribute by opening a PR.
